Program EXEMPLO5 ;
VAR
CPF, XC, DIGITO1, DIGITO2 : STRING;
VCPF : ARRAY[1..14] OF STRING;
TCPF : ARRAY[1..10] OF INTEGER;
INDICE,SOMA, PESO, D1, D2, XV, CODE : INTEGER;

Begin
  
  CLRSCR;
  WRITE('Digite um CPF (999.999.999-99) : ');
  READ(CPF);
  
  IF (LENGTH(CPF) <> 14) THEN
  WRITELN(' TAMANHO DO CPF inválido ! ')
  ELSE BEGIN
    
// PEGAR OS CARACTERES DO 'CPF STRING' E COLOCAR NO VETOR VCPF
    
    FOR INDICE := 1 TO 14 DO BEGIN
      XC := COPY(CPF,INDICE,1);
      VCPF[INDICE] := XC;
    END;
    
// PRIMEIRA ETAPA - CALCULAR O PRIMEIRO DIGITO
    
    XV := 1;
    FOR INDICE := 1 TO 12 DO BEGIN
      XC := VCPF[INDICE];
      IF (XC <> '.') AND (XC <> '-') THEN BEGIN
        VAL(XC,D2,CODE);   //  TRANSFORMA EM UM NÚMERO
        TCPF[XV] := D2;    // COLOCO NO VETOR INTEGER
        XV := XV + 1;      // INCREMENTO O CONTADOR DE INDICE
      END;
    END;
    
// SEGUNDA ETAPA - CALCULAR O SEGUNDO DIGITO VERIFICADOR
    
    SOMA := 0;      // ZERAR A SOMA
    PESO := 10;     // PESO COMEÇA COM O VALOR 10
    
    FOR INDICE := 1 TO 9 DO BEGIN
      SOMA := SOMA + ( TCPF[INDICE] * PESO);
      PESO := PESO - 1;
    END;
    
    D1 := 11 - (SOMA MOD 11);  // SUBTRAIO DE 11 O VALOR DO MÓDULO 11 DA SOMA
    IF D1 < 2 THEN D1 := 0;    // SE FOR MENOR QUE 2, DEVERÁ SER ZERADO
    STR(D1,DIGITO1);           // TRANSFORMANDO EM STRING
    TCPF[10] := D1;            //  ACRENTEI A ÚLTIMA POSIÇÃO DO MEU VETOR
    
    
//  TERCEIRA ETAPA - CALCULAR O SEGUNDO DIGITO
    
    SOMA := 0;      // ZERAR A SOMA
    PESO := 11;     // PESO COMEÇA COM O VALOR 11
    
    FOR INDICE := 1 TO 10 DO BEGIN
      SOMA := SOMA + ( TCPF[INDICE] * PESO);    // ACUMULANDO EM 'SOMA' O DIGITO MULTIPLICADO PELO PESO
      PESO := PESO - 1;                         // DECREMENTO O VALOR DA VARIÁVEL 'PESO'
    END;
    
    D2 := 11 - (SOMA MOD 11);  // SUBTRAIO DE 11 O VALOR DO MÓDULO 11 DA SOMA
    IF D2 < 2 THEN D2 := 0;    // SE FOR MENOR QUE 2, DEVERÁ SER ZERADO
    STR(D2,DIGITO2);           // TRANSFORMANDO EM STRING
    
    //    QUARTA ETAPA - VERIFICAR
    
    IF (DIGITO1 = VCPF[13]) AND (DIGITO2 = VCPF[14]) THEN
    WRITELN('O CPF está correto!')
    ELSE
    WRITELN('O CPF está INCORRETO!');
    
  END;
  
End.

